// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: proto/handler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SetURLRequest schema to set 1 url
type SetAddrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User         uint32 `protobuf:"fixed32,1,opt,name=user,proto3" json:"user,omitempty"`
	OriginalAddr string `protobuf:"bytes,2,opt,name=original_addr,json=originalAddr,proto3" json:"original_addr,omitempty"`
}

func (x *SetAddrRequest) Reset() {
	*x = SetAddrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAddrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAddrRequest) ProtoMessage() {}

func (x *SetAddrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAddrRequest.ProtoReflect.Descriptor instead.
func (*SetAddrRequest) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{0}
}

func (x *SetAddrRequest) GetUser() uint32 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *SetAddrRequest) GetOriginalAddr() string {
	if x != nil {
		return x.OriginalAddr
	}
	return ""
}

// SetURLResponse schema to return 1 url
type SetAddrResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User   uint32 `protobuf:"fixed32,3,opt,name=user,proto3" json:"user,omitempty"`
	Result string `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SetAddrResponse) Reset() {
	*x = SetAddrResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAddrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAddrResponse) ProtoMessage() {}

func (x *SetAddrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAddrResponse.ProtoReflect.Descriptor instead.
func (*SetAddrResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{1}
}

func (x *SetAddrResponse) GetUser() uint32 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *SetAddrResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// GetURLRequest schema to get 1 full url
type GetAddrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User     uint32 `protobuf:"fixed32,5,opt,name=user,proto3" json:"user,omitempty"`
	Checksum string `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
}

func (x *GetAddrRequest) Reset() {
	*x = GetAddrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddrRequest) ProtoMessage() {}

func (x *GetAddrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddrRequest.ProtoReflect.Descriptor instead.
func (*GetAddrRequest) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{2}
}

func (x *GetAddrRequest) GetUser() uint32 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *GetAddrRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// GetURLResponse schema to return 1 full url
type GetAddrResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalAddr string `protobuf:"bytes,7,opt,name=original_addr,json=originalAddr,proto3" json:"original_addr,omitempty"`
}

func (x *GetAddrResponse) Reset() {
	*x = GetAddrResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddrResponse) ProtoMessage() {}

func (x *GetAddrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddrResponse.ProtoReflect.Descriptor instead.
func (*GetAddrResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{3}
}

func (x *GetAddrResponse) GetOriginalAddr() string {
	if x != nil {
		return x.OriginalAddr
	}
	return ""
}

// URLListItemRequest schema to get an item of urls list
type AddrListItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalAddr  string `protobuf:"bytes,9,opt,name=original_addr,json=originalAddr,proto3" json:"original_addr,omitempty"`
}

func (x *AddrListItemRequest) Reset() {
	*x = AddrListItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddrListItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrListItemRequest) ProtoMessage() {}

func (x *AddrListItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrListItemRequest.ProtoReflect.Descriptor instead.
func (*AddrListItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{4}
}

func (x *AddrListItemRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddrListItemRequest) GetOriginalAddr() string {
	if x != nil {
		return x.OriginalAddr
	}
	return ""
}

// URLListItemRequest
type AddrListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User uint32                 `protobuf:"fixed32,10,opt,name=user,proto3" json:"user,omitempty"`
	List []*AddrListItemRequest `protobuf:"bytes,11,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *AddrListRequest) Reset() {
	*x = AddrListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddrListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrListRequest) ProtoMessage() {}

func (x *AddrListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrListRequest.ProtoReflect.Descriptor instead.
func (*AddrListRequest) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{5}
}

func (x *AddrListRequest) GetUser() uint32 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *AddrListRequest) GetList() []*AddrListItemRequest {
	if x != nil {
		return x.List
	}
	return nil
}

// URLListItemResponse schema to return a list of urls
type AddrListItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,12,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortAddr     string `protobuf:"bytes,13,opt,name=short_addr,json=shortAddr,proto3" json:"short_addr,omitempty"`
}

func (x *AddrListItemResponse) Reset() {
	*x = AddrListItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddrListItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrListItemResponse) ProtoMessage() {}

func (x *AddrListItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrListItemResponse.ProtoReflect.Descriptor instead.
func (*AddrListItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{6}
}

func (x *AddrListItemResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AddrListItemResponse) GetShortAddr() string {
	if x != nil {
		return x.ShortAddr
	}
	return ""
}

type AddrListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User uint32                  `protobuf:"fixed32,14,opt,name=user,proto3" json:"user,omitempty"`
	List []*AddrListItemResponse `protobuf:"bytes,15,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *AddrListResponse) Reset() {
	*x = AddrListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddrListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrListResponse) ProtoMessage() {}

func (x *AddrListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrListResponse.ProtoReflect.Descriptor instead.
func (*AddrListResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{7}
}

func (x *AddrListResponse) GetUser() uint32 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *AddrListResponse) GetList() []*AddrListItemResponse {
	if x != nil {
		return x.List
	}
	return nil
}

type AddrFullInfoListItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortAddr    string `protobuf:"bytes,16,opt,name=short_addr,json=shortAddr,proto3" json:"short_addr,omitempty"`
	OriginalAddr string `protobuf:"bytes,17,opt,name=original_addr,json=originalAddr,proto3" json:"original_addr,omitempty"`
}

func (x *AddrFullInfoListItemResponse) Reset() {
	*x = AddrFullInfoListItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddrFullInfoListItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrFullInfoListItemResponse) ProtoMessage() {}

func (x *AddrFullInfoListItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrFullInfoListItemResponse.ProtoReflect.Descriptor instead.
func (*AddrFullInfoListItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{8}
}

func (x *AddrFullInfoListItemResponse) GetShortAddr() string {
	if x != nil {
		return x.ShortAddr
	}
	return ""
}

func (x *AddrFullInfoListItemResponse) GetOriginalAddr() string {
	if x != nil {
		return x.OriginalAddr
	}
	return ""
}

type AddrFullInfoListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*AddrFullInfoListItemResponse `protobuf:"bytes,18,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *AddrFullInfoListResponse) Reset() {
	*x = AddrFullInfoListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddrFullInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrFullInfoListResponse) ProtoMessage() {}

func (x *AddrFullInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrFullInfoListResponse.ProtoReflect.Descriptor instead.
func (*AddrFullInfoListResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{9}
}

func (x *AddrFullInfoListResponse) GetList() []*AddrFullInfoListItemResponse {
	if x != nil {
		return x.List
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User uint32 `protobuf:"fixed32,19,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{10}
}

func (x *UserInfo) GetUser() uint32 {
	if x != nil {
		return x.User
	}
	return 0
}

type DeleteBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User         uint32   `protobuf:"fixed32,20,opt,name=user,proto3" json:"user,omitempty"`
	ChecksumList []string `protobuf:"bytes,21,rep,name=checksum_list,json=checksumList,proto3" json:"checksum_list,omitempty"`
}

func (x *DeleteBatchRequest) Reset() {
	*x = DeleteBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBatchRequest) ProtoMessage() {}

func (x *DeleteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBatchRequest.ProtoReflect.Descriptor instead.
func (*DeleteBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteBatchRequest) GetUser() uint32 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *DeleteBatchRequest) GetChecksumList() []string {
	if x != nil {
		return x.ChecksumList
	}
	return nil
}

type TextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,22,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *TextResponse) Reset() {
	*x = TextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResponse) ProtoMessage() {}

func (x *TextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResponse.ProtoReflect.Descriptor instead.
func (*TextResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{12}
}

func (x *TextResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type StatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{13}
}

type StatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NAddr  uint32 `protobuf:"fixed32,24,opt,name=n_addr,json=nAddr,proto3" json:"n_addr,omitempty"`
	NUsers uint32 `protobuf:"fixed32,25,opt,name=n_users,json=nUsers,proto3" json:"n_users,omitempty"`
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_proto_rawDescGZIP(), []int{14}
}

func (x *StatsResponse) GetNAddr() uint32 {
	if x != nil {
		return x.NAddr
	}
	return 0
}

func (x *StatsResponse) GetNUsers() uint32 {
	if x != nil {
		return x.NUsers
	}
	return 0
}

var File_proto_handler_proto protoreflect.FileDescriptor

var file_proto_handler_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x0e,
	0x53, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x22, 0x3d, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x40, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x22, 0x36, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x41, 0x64, 0x64, 0x72,
	0x22, 0x61, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x41,
	0x64, 0x64, 0x72, 0x22, 0x55, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x41, 0x64, 0x64, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x5c, 0x0a, 0x14, 0x41, 0x64,
	0x64, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x41, 0x64, 0x64, 0x72, 0x22, 0x57, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x12, 0x2f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x22, 0x62, 0x0a, 0x1c, 0x41, 0x64, 0x64, 0x72, 0x46, 0x75, 0x6c, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61,
	0x6c, 0x41, 0x64, 0x64, 0x72, 0x22, 0x53, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x72, 0x46, 0x75, 0x6c,
	0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x37, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x12, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x46, 0x75, 0x6c, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x1e, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x13,
	0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x4d, 0x0a, 0x12, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x14, 0x20, 0x01, 0x28, 0x07, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x15, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x73, 0x75, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x0c, 0x54, 0x65, 0x78,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x16, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x3f, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x18, 0x20, 0x01, 0x28,
	0x07, 0x52, 0x05, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x18, 0x19, 0x20, 0x01, 0x28, 0x07, 0x52, 0x06, 0x6e, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x32, 0xf5, 0x02, 0x0a, 0x04, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x37, 0x0a, 0x06, 0x53, 0x65,
	0x74, 0x55, 0x52, 0x4c, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74,
	0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x46, 0x75, 0x6c, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x42, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6e, 0x6e, 0x56, 0x30, 0x6c, 0x6f, 0x6b,
	0x69, 0x74, 0x69, 0x6e, 0x61, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x2d, 0x75, 0x72, 0x6c, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_handler_proto_rawDescOnce sync.Once
	file_proto_handler_proto_rawDescData = file_proto_handler_proto_rawDesc
)

func file_proto_handler_proto_rawDescGZIP() []byte {
	file_proto_handler_proto_rawDescOnce.Do(func() {
		file_proto_handler_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_handler_proto_rawDescData)
	})
	return file_proto_handler_proto_rawDescData
}

var file_proto_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_handler_proto_goTypes = []interface{}{
	(*SetAddrRequest)(nil),               // 0: proto.SetAddrRequest
	(*SetAddrResponse)(nil),              // 1: proto.SetAddrResponse
	(*GetAddrRequest)(nil),               // 2: proto.GetAddrRequest
	(*GetAddrResponse)(nil),              // 3: proto.GetAddrResponse
	(*AddrListItemRequest)(nil),          // 4: proto.AddrListItemRequest
	(*AddrListRequest)(nil),              // 5: proto.AddrListRequest
	(*AddrListItemResponse)(nil),         // 6: proto.AddrListItemResponse
	(*AddrListResponse)(nil),             // 7: proto.AddrListResponse
	(*AddrFullInfoListItemResponse)(nil), // 8: proto.AddrFullInfoListItemResponse
	(*AddrFullInfoListResponse)(nil),     // 9: proto.AddrFullInfoListResponse
	(*UserInfo)(nil),                     // 10: proto.UserInfo
	(*DeleteBatchRequest)(nil),           // 11: proto.DeleteBatchRequest
	(*TextResponse)(nil),                 // 12: proto.TextResponse
	(*StatRequest)(nil),                  // 13: proto.StatRequest
	(*StatsResponse)(nil),                // 14: proto.StatsResponse
}
var file_proto_handler_proto_depIdxs = []int32{
	4,  // 0: proto.AddrListRequest.list:type_name -> proto.AddrListItemRequest
	6,  // 1: proto.AddrListResponse.list:type_name -> proto.AddrListItemResponse
	8,  // 2: proto.AddrFullInfoListResponse.list:type_name -> proto.AddrFullInfoListItemResponse
	0,  // 3: proto.URLs.SetURL:input_type -> proto.SetAddrRequest
	2,  // 4: proto.URLs.GetURL:input_type -> proto.GetAddrRequest
	10, // 5: proto.URLs.GetUserURLList:input_type -> proto.UserInfo
	5,  // 6: proto.URLs.SetShortenBatch:input_type -> proto.AddrListRequest
	11, // 7: proto.URLs.DeleteBatch:input_type -> proto.DeleteBatchRequest
	13, // 8: proto.URLs.GetStats:input_type -> proto.StatRequest
	1,  // 9: proto.URLs.SetURL:output_type -> proto.SetAddrResponse
	3,  // 10: proto.URLs.GetURL:output_type -> proto.GetAddrResponse
	9,  // 11: proto.URLs.GetUserURLList:output_type -> proto.AddrFullInfoListResponse
	7,  // 12: proto.URLs.SetShortenBatch:output_type -> proto.AddrListResponse
	12, // 13: proto.URLs.DeleteBatch:output_type -> proto.TextResponse
	14, // 14: proto.URLs.GetStats:output_type -> proto.StatsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_handler_proto_init() }
func file_proto_handler_proto_init() {
	if File_proto_handler_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_handler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAddrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAddrResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddrResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddrListItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddrListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddrListItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddrListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddrFullInfoListItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddrFullInfoListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_handler_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_handler_proto_goTypes,
		DependencyIndexes: file_proto_handler_proto_depIdxs,
		MessageInfos:      file_proto_handler_proto_msgTypes,
	}.Build()
	File_proto_handler_proto = out.File
	file_proto_handler_proto_rawDesc = nil
	file_proto_handler_proto_goTypes = nil
	file_proto_handler_proto_depIdxs = nil
}
